language: python
# os: linux
python:
  - 3.5
  # - 3.6
sudo: true

services:
  - postgresql

before_script:
  - psql -c 'create database parkour;' -U postgres
  - mkdir /home/travis/build/maxplanck-ie/parkour/logs

install: pip install -r requirements/prod.txt

script: python manage.py test

notifications:
  email: false
