language: python
os: linux
python:
  - 3.5
  # - 3.6
  
services:
  - postgresql

before_script:
  - psql -c 'create database parkour;' -U postgres

install: pip install -r requirements.txt

script: python manage.py test
